spring:
  application:
    name: BLOG-API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: BLOG-AUTH-SERVER
          uri: lb://BLOG-AUTH-SERVER
          predicates:
            - Path=/api/v1.0/blogsite/auth/**
          filters:
            - AuthenticationFilter

        - id: BLOG-AUTH-SERVER
          uri: lb://BLOG-AUTH-SERVER
          predicates:
            - Path=/api/v1.0/blog/user/**
          filters:
            - AuthenticationFilter

        - id: BLOG-USER-SERVICE
          uri: lb://BLOG-USER-SERVICE
          predicates:
            - Path=/api/v1.0/user/**
          filters:
            - AuthenticationFilter

server:
  port: ${port:8080}


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
